### ISSUE TITLE
First round of graduating nodes from `node-nursery`

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#123]
Candidates:

- `createVectorDatabase` -- stays put
- `addToVectorDatabase` -- stays put
- `queryVectorDatabase` -- stays put
- `embedDocs` -- stays put
- [x] `embedString` -- graduates as `embedText` to `LLM Starter Kit`
- `cache` -- stays put
- `textAsset` -- stays put
- `textAssetsFromPath` -- stays put
- [x] `vars` -- remove
- [x] `localMemory` -- remove
- [x] `validateJson` -- graduates to `JSON Kit` (see google/breadboard-ai#122)
- [x] `schemish` -- graduates to `JSON Kit` (see google/breadboard-ai#122)
- `templateParser` -- stays put
- [x] `map` -- graduates to `Core Kit` (see google/breadboard-ai#105)
- [x] `batcher` -- graduates to `Core Kit` as `batch` (see google/breadboard-ai#105)
- [ ] `chunker` -- graduates to `LLM Starter Kit`.

**Comment by dglazkov** [comment]
Declaring victory 🚢
