### ISSUE TITLE
Remote Board Manifest Provider

### ISSUE THREAD

**Issue by Mearman** [breadboard-ai/breadboard#2152]
To enhance the development workflow and reduce friction for code-first development, we propose implementing a “Remote Board Manifest Provider.” This provider will enable loading board definitions from remote sources such as Gist or GitHub repositories. The initial focus will be on supporting Gist, with potential future expansions to other platforms like GitHub or any other files server.

### Key Features
1. **Gist Provider**:
   - Ability to load board definitions from a Gist.
   - Support for multiple files within a Gist, allowing for complex board setups.
   - Fetch requests to Gist API to retrieve necessary files.
   - Handling CORS errors and ensuring seamless data fetching.

2. **Manifest File**:
   - Use a manifest file to list all available board JSON files.
   - Support for both relative paths (within the Gist) and absolute URLs (any valid JSON URL).
   - The provider itself could be the manifest file, enhancing flexibility and usability.

3. **Future Expansions**:
   - Potential support for GitHub repository providers, requiring a specific repo structure.
   - Auto-generation of manifests from code-first repositories.

### Implementation Steps
1. **Gist Fetching**:
   - Implement fetching of JSON files from a Gist using the Gist API.
   - Ensure correct handling of CORS and other potential issues.
   - Example fetch request for a single file:
```javascript
await (await fetch("https://gist.githubusercontent.com/username/gist_id/raw/commit_id/filename.json")).json();
```

2. **Manifest Handling**:
   - Implement parsing and fetching logic for the manifest file.
   - Example manifest structure based on [breadboard-web/public/local-boards.json](https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard-web/public/local-boards.json
)
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Breadboard Board Manifest",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "title": {
        "type": "string"
      },
      "url": {
        "type": "string"
      },
      "version": {
        "type": "string"
      }
    },
    "required": [
      "title",
      "url"
    ]
  }
}
```

3. **Provider Logic**:
   - Develop the provider logic to handle the manifest file and fetch listed boards.
   - Support both relative and absolute URLs in the manifest.

### Potential Challenges
- Handling CORS issues when fetching data from remote sources.
- Ensuring reliable and secure fetching of JSON files.
- Maintaining compatibility with future expansions (e.g., GitHub provider).

### Task List
- [ ] Implement fetching of JSON files from Gist.
- [ ] Develop and test the manifest file structure.
- [ ] Implement provider logic to handle manifest and fetch boards.
- [ ] Handle CORS and other potential issues.
- [ ] Plan for future expansions to support other platforms.

### Notes
- The initial implementation will focus on read-only access via Gist.
- The manifest file could serve as the provider, listing all necessary board files.
- Future enhancements could include auto-generating manifests from code-first repositories.
