### ISSUE TITLE
☂️ Support Standalone Node Runs

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#3465]
## TODO

 - [x] Update edge rendering
 - [x] Add support for changing values on the wire
 - [x] Add UI controls
 - [x] Add Component Footer and move activity marker there
 - [x] Add Run Component button and trigger run overlay

## Done
