### ISSUE TITLE
Document project architecture and roadmap

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#908]
- [ ] Finish [conceptual overview](https://breadboard-ai.github.io/breadboard/docs/too-long/) 
- [ ] Document concrete implementation of concepts (typescript framework, python frontend)
- [ ] Write TS framework overview
  - framework + tools + apps
  - high-level overview of the framework (a collection of APIs)
  - What are tools?
  - How does everything work together 
 - [ ] The framework details
   - the actual APIs overview
   - a bit on the innards maybe?
- [ ] Roadmap: where do we want to go?
  - What is complete and what is not
